USE SQL_PRACTICE;

select * from customers;
select * from orders;
select * from products;

-- 1. Find the total quantity of each product sold.
select t2.product_id, sum(t1.quantity) as 'total_quantity_sold'
from orders t1
join products t2
on t1.product_id = t2.product_id
group by product_id
order by total_quantity_sold DESC LIMIT 5;

-- 2. List the top 5 countries with the highest number of orders.
select c1.country, SUM(o1.quantity), COUNT(o1.order_id)
from orders o1
right join customers c1
on c1.customer_id = o1.customer_id
group by c1.country
order by SUM(o1.quantity) desc limit 5;

-- 3.  Find customers who have placed at least 3 orders and show their average order value.
select c1.customer_id, COUNT(o1.order_id) as 'total_order_count'
from products p1
join orders o1
on o1.product_id = p1.product_id
join customers c1
on c1.customer_id = o1.customer_id
group by c1.customer_id
order by total_order_count desc limit 3;


-- 4. Show total revenue generated by each product category.
select category, 
round(sum(price),2) as 'total_price'
from products
group by category;

-- 5. Identify the most popular product in each category based on total quantity sold.
select category, sum(o1.quantity) as total_quantity_sold
from products p1
join orders o1
on o1.product_id = p1.product_id
group by category
order by total_quantity_sold desc limit 3

-- 6. Rank all customers by their total purchase amount (most to least).

-- 7. Display total sales revenue for each month of the year.

-- 8. Find products that generated more than $10,000 in total revenue.

-- 9. Find the average order value grouped by customer country.

-- 10. Rank customers within each country based on total spending.


